# 本地开发环境配置
spring:
  datasource:
    url: jdbc:sqlserver://bogdatechtestsqlserver.database.windows.net:1433;database=bogdatech-test;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: bogdatechtestsqlserver@bogdatechtestsqlserver
    password: Hyw124563

  # Redis 配置（本地开发环境默认配置）
#  redis:
#    host: localhost            # Redis 服务器地址
#    port: 6379                 # Redis 默认端口
#    password:                   # 本地开发通常不设密码，如果有密码则填写
#    database: 0                 # 默认使用 0 号数据库（0-15）
#    timeout: 3000ms             # 连接超时时间
#    jedis:
#      pool:
#        max-active: 8           # 连接池最大连接数
#        max-idle: 8             # 连接池最大空闲连接数
#        min-idle: 0             # 连接池最小空闲连接数
#        max-wait: -1ms          # 连接池最大等待时间（-1 表示无限等待）

management:
  health:
    redis:
      enabled: false  # 禁用 Redis 健康检查（如果未配置 Redis）

#
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
